const app = document.querySelector('#app');
const money = amount => new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR' }).format(Number(amount || 0));
const dateFormat = date => new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${date}T00:00:00`));
const escapeHTML = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
let state = { user: null, expenses: [], route: 'dashboard', selectedId: null, authMode: 'login' };

const nav = () => `<nav class="navbar navbar-expand-lg py-3"><div class="container"><a class="navbar-brand" href="#dashboard" data-route="dashboard"><span class="brand-mark">F</span> fairshare</a>${state.user ? `<div class="d-flex align-items-center gap-3"><a class="nav-link d-none d-sm-block" href="#history" data-route="history">History</a><a class="btn btn-primary rounded-pill px-4" href="#create" data-route="create"><i class="bi bi-plus-lg me-2"></i>New expense</a><button class="avatar" id="logout" title="Log out">${escapeHTML((state.user.name || state.user.username)[0].toUpperCase())}</button></div>` : ''}</div></nav>`;
const pageShell = content => `${nav()}<main class="container page-wrap">${content}</main>`;
const empty = (icon, title, text, action) => `<div class="empty-state"><div class="empty-icon"><i class="bi ${icon}"></i></div><h3>${title}</h3><p>${text}</p>${action || ''}</div>`;

function authView() {
  return `<div class="auth-page"><div class="auth-copy"><a class="navbar-brand" href="#"><span class="brand-mark">F</span> fairshare</a><div class="auth-quote"><span class="eyebrow">EXPENSES, UNTANGLED</span><h1>Good friends<br><em>keep it fair.</em></h1><p>Split shared expenses without the awkward maths. Simple, clear, and ready when you are.</p></div><div class="auth-foot"><i class="bi bi-shield-check me-2"></i>Your data stays in your browser for now.</div></div><div class="auth-form"><div class="mobile-brand"><span class="brand-mark">F</span> fairshare</div><div class="form-width"><span class="eyebrow">WELCOME TO FAIRSHARE</span><h2>${state.authMode === 'login' ? 'Welcome back.' : 'Create your account.'}</h2><p class="muted mb-4">${state.authMode === 'login' ? 'Log in to see your expenses.' : 'Start keeping shared spending simple.'}</p><div id="auth-error"></div>${state.authMode === 'register' ? `<label class="form-label">Your name</label><input class="form-control mb-3" id="name" placeholder="e.g. Maya Chen">` : ''}<label class="form-label">Username</label><input class="form-control mb-3" id="username" placeholder="e.g. maya" autocomplete="username"><label class="form-label">Password</label><input type="password" class="form-control mb-4" id="password" placeholder="••••••••" autocomplete="current-password"><button class="btn btn-primary w-100 py-3 rounded-3" id="auth-submit">${state.authMode === 'login' ? 'Log in' : 'Create account'} <i class="bi bi-arrow-right ms-2"></i></button><p class="switch-auth">${state.authMode === 'login' ? 'New to FairShare?' : 'Already have an account?'} <button id="switch-auth">${state.authMode === 'login' ? 'Create an account' : 'Log in'}</button></p>${state.authMode === 'login' ? `<div class="demo-hint"><i class="bi bi-lightbulb"></i><span>Try the demo with <strong>demo</strong> / <strong>demo</strong></span></div>` : ''}</div></div></div>`;
}

function dashboard() {
  const recent = state.expenses.slice(0, 5);
  return pageShell(`<section class="hero-row"><div><span class="eyebrow">${new Date().toLocaleDateString('en-GB', { weekday: 'long', month: 'long', day: 'numeric' })}</span><h1>Good to see you, <em>${escapeHTML((state.user.name || state.user.username).split(' ')[0])}.</em></h1><p class="lead muted">Keep every shared expense feeling easy.</p></div><a href="#create" data-route="create" class="btn btn-primary btn-lg rounded-3 px-4"><i class="bi bi-plus-lg me-2"></i>Create expense</a></section><div class="section-heading"><div><h2>Recent expenses</h2><p class="muted">Your five latest splits</p></div><a href="#history" data-route="history" class="text-link">View all <i class="bi bi-arrow-up-right"></i></a></div>${recent.length ? `<div class="expense-list">${recent.map(expenseRow).join('')}</div>` : empty('bi-receipt', 'Nothing here yet', 'Create your first shared expense to see it here.', '<a href="#create" data-route="create" class="btn btn-primary rounded-pill px-4">Create expense</a>')}`);
}
function expenseRow(expense) { return `<a class="expense-row" href="#expense/${expense.id}" data-expense="${expense.id}"><div class="expense-date">${dateFormat(expense.date).split(' ')[0]}<small>${dateFormat(expense.date).split(' ').slice(1).join(' ')}</small></div><div class="expense-info"><strong>${escapeHTML(expense.title)}</strong><span>${expense.participants.length} people · Paid by ${escapeHTML(expense.payer)}</span></div><strong class="expense-total">${money(expense.total)}</strong><i class="bi bi-chevron-right row-arrow"></i></a>`; }

function createView() { return pageShell(`<div class="narrow-page"><a href="#dashboard" data-route="dashboard" class="back-link"><i class="bi bi-arrow-left"></i> Back to dashboard</a><span class="eyebrow">NEW EXPENSE</span><h1>Let's split it.</h1><p class="lead muted mb-5">Add the details and we'll handle the maths.</p><form id="expense-form"><div id="form-error"></div><div class="card form-card mb-4"><div class="card-body"><h3>Expense details</h3><div class="row g-3"><div class="col-md-8"><label class="form-label">What was it for?</label><input class="form-control" id="title" placeholder="e.g. Dinner at Luigi's" required></div><div class="col-md-4"><label class="form-label">Total <span class="currency">EUR</span></label><div class="input-group"><span class="input-group-text">€</span><input type="number" step="0.01" min="0.01" class="form-control" id="total" placeholder="0.00" required></div></div><div class="col-md-5"><label class="form-label">Date</label><input type="date" class="form-control" id="date" value="${new Date().toISOString().slice(0, 10)}" required></div><div class="col-md-7"><label class="form-label">Note <span class="optional">optional</span></label><input class="form-control" id="note" placeholder="Add a little context"></div></div></div></div><div class="card form-card mb-4"><div class="card-body"><div class="d-flex justify-content-between align-items-start"><div><h3>Who's involved?</h3><p class="muted small">Add everyone, including the person who paid.</p></div><button type="button" class="btn btn-light rounded-pill" id="add-person"><i class="bi bi-plus-lg me-1"></i> Add person</button></div><div id="people-list"></div></div></div><div class="card form-card mb-4"><div class="card-body"><h3>How should it be split?</h3><div class="split-options"><label class="split-option active"><input type="radio" name="split" value="equal" checked><span><strong>Split equally</strong><small>Everyone pays the same share</small></span><i class="bi bi-check-circle-fill"></i></label><label class="split-option"><input type="radio" name="split" value="custom"><span><strong>Custom amounts</strong><small>Set each person's exact share</small></span><i class="bi bi-circle"></i></label></div><div id="custom-hint" class="custom-hint d-none"><i class="bi bi-info-circle me-2"></i>Enter an amount for each person. They must add up to the total.</div></div></div><div class="d-flex justify-content-end gap-3"><a href="#dashboard" data-route="dashboard" class="btn btn-light rounded-3 px-4">Cancel</a><button class="btn btn-primary rounded-3 px-5" type="submit">See the split <i class="bi bi-arrow-right ms-2"></i></button></div></form></div>`); }

function resultView(expense) { if (!expense) return pageShell(empty('bi-search', 'Expense not found', 'This expense may have been deleted.', '<a href="#dashboard" data-route="dashboard" class="btn btn-primary rounded-pill px-4">Back home</a>')); const debts = expense.participants.filter(p => !p.isPayer && p.share > 0); return pageShell(`<div class="narrow-page"><div class="result-top"><a href="#dashboard" data-route="dashboard" class="back-link"><i class="bi bi-arrow-left"></i> Dashboard</a><button class="btn btn-light rounded-pill" data-delete="${expense.id}"><i class="bi bi-trash3 me-1"></i> Delete</button></div><div class="result-header"><div class="success-mark"><i class="bi bi-check-lg"></i></div><span class="eyebrow">SPLIT SAVED</span><h1>${escapeHTML(expense.title)}</h1><p class="muted">${dateFormat(expense.date)} ${expense.note ? `· ${escapeHTML(expense.note)}` : ''}</p></div><div class="total-card"><span>Total expense</span><strong>${money(expense.total)}</strong><small>Paid by ${escapeHTML(expense.payer)}</small></div><div class="result-card"><div class="result-card-head"><h3>Everyone's share</h3><span class="badge-soft">${expense.splitType === 'equal' ? 'Equal split' : 'Custom split'}</span></div>${expense.participants.map(p => `<div class="share-row"><div class="person-avatar">${escapeHTML(p.name[0].toUpperCase())}</div><div class="share-person"><strong>${escapeHTML(p.name)} ${p.isPayer ? '<span class="payer-tag">payer</span>' : ''}</strong><small>${p.isPayer ? 'Paid the full expense' : 'Owes their share'}</small></div><strong>${money(p.share)}</strong></div>`).join('')}</div><div class="result-card"><div class="result-card-head"><h3>Who owes whom</h3><i class="bi bi-arrow-left-right muted"></i></div>${debts.length ? debts.map(p => `<div class="debt-row"><span>${escapeHTML(p.name)}</span><i class="bi bi-arrow-right"></i><strong>${escapeHTML(expense.payer)}</strong><b>${money(p.share)}</b></div>`).join('') : '<p class="muted mb-0">Everyone is settled up.</p>'}</div></div>`); }
function historyView() { return pageShell(`<div class="section-heading history-heading"><div><span class="eyebrow">YOUR ACTIVITY</span><h1>Expense history</h1><p class="muted">Every split, all in one place.</p></div><a href="#create" data-route="create" class="btn btn-primary rounded-3 px-4"><i class="bi bi-plus-lg me-2"></i>New expense</a></div>${state.expenses.length ? `<div class="expense-list history-list">${state.expenses.map(expenseRow).join('')}</div>` : empty('bi-clock-history', 'No expenses yet', 'Your saved expenses will appear here.')}`); }

function render() { app.innerHTML = state.user ? (state.route === 'create' ? createView() : state.route === 'history' ? historyView() : state.route === 'expense' ? resultView(state.expenses.find(e => e.id === state.selectedId)) : dashboard()) : authView(); bind(); }
async function load() { state.user = await FairShareAPI.currentUser(); if (state.user) state.expenses = await FairShareAPI.listExpenses(); render(); }
function showToast(message, type = 'success') { document.querySelector('#toast-container').innerHTML = `<div class="toast show align-items-center border-0 toast-${type}" role="alert"><div class="d-flex"><div class="toast-body"><i class="bi ${type === 'success' ? 'bi-check-circle' : 'bi-exclamation-circle'} me-2"></i>${escapeHTML(message)}</div><button type="button" class="btn-close me-2 m-auto" onclick="this.closest('.toast').remove()"></button></div></div>`; }
function peopleHTML() { return `<div class="person-row"><span class="person-number">01</span><input class="form-control person-name" placeholder="Person's name" required><label class="payer-select"><input type="radio" name="payer" checked> <span>Paid</span></label><input class="form-control custom-amount d-none" type="number" min="0" step="0.01" placeholder="€ 0.00"></div><div class="person-row"><span class="person-number">02</span><input class="form-control person-name" placeholder="Person's name" required><label class="payer-select"><input type="radio" name="payer"> <span>Paid</span></label><input class="form-control custom-amount d-none" type="number" min="0" step="0.01" placeholder="€ 0.00"></div>`; }
function bind() {
  document.querySelectorAll('[data-route]').forEach(el => el.onclick = e => { e.preventDefault(); state.route = el.dataset.route; render(); });
  document.querySelectorAll('[data-expense]').forEach(el => el.onclick = e => { e.preventDefault(); state.route = 'expense'; state.selectedId = el.dataset.expense; render(); });
  document.querySelectorAll('[data-delete]').forEach(el => el.onclick = async () => { if (confirm('Delete this expense? This cannot be undone.')) { await FairShareAPI.deleteExpense(el.dataset.delete); state.expenses = await FairShareAPI.listExpenses(); state.route = 'dashboard'; render(); showToast('Expense deleted.'); } });
  const logout = document.querySelector('#logout'); if (logout) logout.onclick = async () => { await FairShareAPI.logout(); state.user = null; render(); };
  const authSubmit = document.querySelector('#auth-submit'); if (authSubmit) authSubmit.onclick = async () => { const username = document.querySelector('#username').value.trim(); const password = document.querySelector('#password').value; const name = document.querySelector('#name')?.value.trim(); if (!username || !password || (state.authMode === 'register' && !name)) return document.querySelector('#auth-error').innerHTML = '<div class="alert alert-danger py-2">Please complete all fields.</div>'; try { state.user = state.authMode === 'login' ? await FairShareAPI.login({ username, password }) : await FairShareAPI.register({ username, password, name }); state.expenses = await FairShareAPI.listExpenses(); state.route = 'dashboard'; render(); } catch (error) { document.querySelector('#auth-error').innerHTML = `<div class="alert alert-danger py-2">${escapeHTML(error.message)}</div>`; } };
  const switchAuth = document.querySelector('#switch-auth'); if (switchAuth) switchAuth.onclick = () => { state.authMode = state.authMode === 'login' ? 'register' : 'login'; render(); };
  const people = document.querySelector('#people-list'); if (people) { people.innerHTML = peopleHTML(); document.querySelector('#add-person').onclick = () => { const count = people.querySelectorAll('.person-row').length + 1; people.insertAdjacentHTML('beforeend', `<div class="person-row"><span class="person-number">${String(count).padStart(2, '0')}</span><input class="form-control person-name" placeholder="Person's name" required><label class="payer-select"><input type="radio" name="payer"> <span>Paid</span></label><input class="form-control custom-amount d-none" type="number" min="0" step="0.01" placeholder="€ 0.00"><button type="button" class="remove-person"><i class="bi bi-x-lg"></i></button></div>`); updateCustom(); }; people.addEventListener('click', e => { if (e.target.closest('.remove-person')) { e.target.closest('.person-row').remove(); people.querySelectorAll('.person-number').forEach((n, i) => n.textContent = String(i + 1).padStart(2, '0')); } }); }
  document.querySelectorAll('input[name="split"]').forEach(input => input.onchange = updateCustom); document.querySelectorAll('.split-option').forEach(label => label.onclick = () => { document.querySelectorAll('.split-option').forEach(item => item.classList.remove('active')); label.classList.add('active'); });
  const form = document.querySelector('#expense-form'); if (form) form.onsubmit = async e => { e.preventDefault(); const names = [...document.querySelectorAll('.person-name')].map(input => input.value.trim()); const total = Number(document.querySelector('#total').value); const payerIndex = [...document.querySelectorAll('input[name="payer"]')].findIndex(input => input.checked); const splitType = document.querySelector('input[name="split"]:checked').value; const error = message => document.querySelector('#form-error').innerHTML = `<div class="alert alert-danger mb-4"><i class="bi bi-exclamation-circle me-2"></i>${message}</div>`; if (names.length < 2 || names.some(name => !name)) return error('Add at least two people and give everyone a name.'); if (!total || total <= 0) return error('Enter a total amount greater than €0.'); let shares; if (splitType === 'equal') { const cents = Math.round(total * 100); const base = Math.floor(cents / names.length); shares = names.map((_, i) => (base + (i === names.length - 1 ? cents - base * names.length : 0)) / 100); } else { shares = [...document.querySelectorAll('.custom-amount')].map(input => Number(input.value)); if (shares.some(amount => amount < 0) || Math.abs(shares.reduce((a, b) => a + b, 0) - total) > 0.001) return error(`Custom amounts must add up to ${money(total)}.`); } const expense = await FairShareAPI.createExpense({ title: document.querySelector('#title').value.trim(), total, date: document.querySelector('#date').value, note: document.querySelector('#note').value.trim(), splitType, payer: names[payerIndex], participants: names.map((name, i) => ({ name, share: shares[i], isPayer: i === payerIndex })) }); state.expenses = await FairShareAPI.listExpenses(); state.route = 'expense'; state.selectedId = expense.id; render(); showToast('Expense saved successfully.'); };
}
function updateCustom() { const custom = document.querySelector('input[name="split"]:checked')?.value === 'custom'; document.querySelectorAll('.custom-amount').forEach(input => input.classList.toggle('d-none', !custom)); document.querySelector('#custom-hint')?.classList.toggle('d-none', !custom); }
window.addEventListener('hashchange', () => { const hash = location.hash.slice(1); if (hash.startsWith('expense/')) { state.route = 'expense'; state.selectedId = hash.split('/')[1]; } else if (['dashboard', 'create', 'history'].includes(hash)) state.route = hash; render(); });
load();
